services:
    backend:
      build: .
      env_file: ./.env
      ports: 
        - 3000:3000
      depends_on: 
        mongo:
          condition: service_started
          restart: true

    mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - db_volume:/data/db
            
volumes:
  db_volume: